### ISSUE TITLE
Plan semantic harmonisation activities

### ISSUE THREAD

**Issue by pbuttigieg** [ESIPFed/SOI_harmonization#7]
Hi all - we've spoken about this in our ESIP calls, but the need is growing to do something concrete to help along implementations such as these https://github.com/EnvironmentOntology/envo/pull/1352 

A SOI / Semantic Harmonization cluster work plan should be planned - even if this is a modest start, it would be significant.

@ktoddbrown @garybc @rduerr

**Comment by ktoddbrown** [comment]
I'm open to this and excited about it. I'm less clear on what the exact plan of attack would be. How would we start here?

**Comment by pbuttigieg** [comment]
The first step, I think, is to identify a few soil classification systems (from the US, EU, Aus, etc) that we'd like to harmonise. 

We'd then start comparing and contrasting the terms and definitions and seeing if we can develop generalised superclasses for them that accommodate the variability. 

Semantic harmonisation has its cyro, marine, and disasters stack already, so I'm not sure how and where to find the time. I think if we find a small subgroup keen on soils they can have a few hackathons or a regular mini-hackathon and then get advice from both the clusters.

**Comment by ktoddbrown** [comment]
While this is a worthy project, I'm not sure it's as fruitful for data purposes as something that is more measurement focused. Having a way to describe the observed properties (as opposed to the taxon classification) might be a good first step to then sort out how these taxon classifications interact.

**Comment by pbuttigieg** [comment]
Okay - ENVO will keep working on this with the valuable input of @dr-shorthair, @smrgeoinfo, and others. 

As far as observed properties, we consider this pretty easy once you set up the higher-level structures like aligned taxonomies. For example, our pattern modules generate classes like [this](https://www.ebi.ac.uk/ols/search?q=in+soil&ontology=envo), and we can create more quite easily. It's mostly about a coherent representation strategy.

**Comment by pbuttigieg** [comment]
Shelving this for now. 

@dr-shorthair @marieALaporte @smrgeoinfo - happy to continue harmonisation over in ENVO until the SOI decides to engage.
